### ISSUE TITLE
Doesn't work with PhantomJS 2.0

### ISSUE THREAD

**Issue by ghost** [vitalie/webshot#10]
Cliver::Dependency::VersionMismatch: Could not find an executable 'phantomjs' that matched the requirements '~> 1.8', '>= 1.8.1'. Found versions were {"/usr/local/bin/phantomjs"=>"2.0.0"}.

**Comment by vitalie** [comment]
You need to downgrade your PhantomJS or use $PATH to specify alternative binary with a higher priority.

**Comment by reidblomquist** [comment]
In all seriousness though @vitalie can you give a brief overview of what you think would go into getting this to work with 2.0; would be nice to get it updated to work with current version of PhantomJS and I'd be more than happy to help get it there!

**Comment by reidblomquist** [comment]
Okay; did a little digging - looks like the holdup is actually on poltergeist's end and it doesn't look as though it'll be resolved anytime soon. Sauce: https://github.com/teampoltergeist/poltergeist/issues/574

**Comment by bytenel** [comment]
+1

**Comment by mgrachev** [comment]
+1

**Comment by reidblomquist** [comment]
.... this isn't an issue with webshot; it's with poltergeist.

**Comment by vitalie** [comment]
Fixed in master branch.
