### ISSUE TITLE
Feature Request: webshot pages with 4xx response code

### ISSUE THREAD

**Issue by syntacticvexation** [vitalie/webshot#11]
Is it possible to have a configuration option to enable taking a screenshot when there's a 4xx response code?  I see at the moment webshot only takes a screenshot with a 200 or 3xx response code otherwise it throws an error.

**Comment by ragesoss** [comment]
Yes, this is exactly what I came looking for as well.

**Comment by syntacticvexation** [comment]
Awesome, thanks all.
