### ISSUE TITLE
How to crop height to the size of the webpage?

### ISSUE THREAD

**Issue by pmackay** [vitalie/webshot#13]
Is there any way to configure minimagick so that it crops the webpage image to the height of the webpage, rather than specifying an exact height?

**Comment by pmackay** [comment]
Have discovered its possible by using a block to configure settings and not define the height:

```
    ws.capture(row[:page], "#{IMAGES_PATH}/#{name}.png", width: 1028) do |magick|
      magick.combine_options do |c|
        c.background "white"
        c.gravity "north"
        c.quality 85
      end
    end
```

**Comment by rehrumesh** [comment]
@pmackay you saved me from throwing away 2 days of work. Man this should be added in the main README.MD
