### ISSUE TITLE
Poltergeist update

### ISSUE THREAD

**Issue by iMacTia** [vitalie/webshot#16]
Hi,

poltergeist gem version 1.8.0 solved some important bugs regarding an out-of-sync on responses.
I'm referring (for example) to these:

https://github.com/teampoltergeist/poltergeist/issues/683
https://github.com/teampoltergeist/poltergeist/issues/482

Is there any chance the dependency on webshot can be updated to version 1.8.0?

Thanks in advance,

Mattia

**Comment by vitalie** [comment]
Hi,

I've upgraded poltergeist to v1.8.

Vitalie
