### ISSUE TITLE
How to setup webshot width and height

### ISSUE THREAD

**Issue by richthedev** [vitalie/webshot#23]
I see there is a default width and height for the PhantomJS viewport in the Webshot module. But I can't seem to find a way to configure those parameters before taking a screenshot. The screenshot class is a singleton and I don't know how to properly pass data to the initialize method.

**Comment by iamWh1sp3r** [comment]
Found out I just need to set Webshot.height and Webshot.width prior to the screenshot.

**Comment by iamWh1sp3r** [comment]
After some tests, it seems that the above solution does not work after all. It works on the first call to ws.capture but then the dimensions are reset for some reason. Am I missing something?
